---
title: "Clustering"
output: 
  pdf_document:
    toc: true
    toc_depth: 6
date: "2024-12-21"
---

# K-means Clustering

```{r}
stations = read.csv('Ch5_bike_station_locations.csv')
two = kmeans(stations, 2)
two
```

```{r}
market = read.csv('Ch5_age_income_data.csv')
market
```

```{r}
three = kmeans(market[,c(2,3)], 3)
plot(market$age, market$income, col=three$cluster)
```

```{r}
market$age_scale = as.numeric(scale(market$age))
market$inc_scale = as.numeric(scale(market$income))
```

```{r}
three_scale = kmeans(market[, c(4,5)],3)
plot(market$age_scale, market$inc_scale, col=three_scale$cluster,
     main='K-means with Scaling')
```

# Hierachical Clustering

```{r}
set.seed(456)
hc_mod = hclust(dist(market[, 4:5]), method='ward.D2')
hc_mod
```

```{r}
dend = as.dendrogram(hc_mod)
library(dendextend)
dend_six_color = color_branches(dend, k=6)
plot(dend_six_color, leaflab='none', horiz=T, main='Age and Income Dendrogram',
     xlab='Height');abline(v=37.5, lty='dashed',col='blue')
```

```{r}
str(cut(dend, h=37.5)$upper)
```

```{r}
one = kmeans(market[,c(4,5)], 1)
two = kmeans(market[,c(4,5)], 2)
three = kmeans(market[,c(4,5)], 3)
four = kmeans(market[,c(4,5)], 4)
five = kmeans(market[,c(4,5)], 5)
six = kmeans(market[,c(4,5)], 6)
seven = kmeans(market[,c(4,5)], 7)
eight = kmeans(market[,c(4,5)], 8)
nine = kmeans(market[,c(4,5)], 9)
ten = kmeans(market[,c(4,5)], 10)
```

```{r}
optimize <- data.frame(clusters = c(2:10), wss = rep(0, 9))
 optimize[1, 2] <- as.numeric(two$tot.withinss)
 optimize[2, 2] <- as.numeric(three$tot.withinss)
 optimize[3, 2] <- as.numeric(four$tot.withinss)
 optimize[4, 2] <- as.numeric(five$tot.withinss)
 optimize[5, 2] <- as.numeric(six$tot.withinss)
 optimize[6, 2] <- as.numeric(seven$tot.withinss)
 optimize[7, 2] <- as.numeric(eight$tot.withinss)
 optimize[8, 2] <- as.numeric(nine$tot.withinss)
 optimize[9, 2] <- as.numeric(ten$tot.withinss)
 plot(optimize$wss ~ optimize$clusters, type = "b",
     ylim = c(0, 12000), ylab = 'Within Sum of Square Error',
     main = 'Finding Optimal Number of Clusters Based on Error',
     xlab = 'Number of Clusters', pch = 17, col = 'black')
```

```{r}
market$clus5 <- five$cluster
dend_five <- cutree(dend, k = 5)
market$dend5 <- dend_five
market$clus6 <- six$cluster
dend_six <- cutree(dend, k = 6)
market$dend6 <- dend_six

```

```{r}
par(mfrow = c(2, 2), mar = c(3, 4, 4, 2) + 0.1)
plot(market$age, market$income, col = five$cluster,
     pch = five$cluster, xlab = '', main = '5-means Clustering')
plot(market$age, market$income, col = six$cluster, xlab = '',
     ylab = '', pch = six$cluster, main = '6-means Clustering')
par(mar = c(5, 4, 2, 2) + 0.1)
plot(market$age, market$income, col = market$dend5,
     pch = market$dend5, main = 'k = 5 Hierarchical')
plot(market$age, market$income, col = market$dend6, ylab = '',
     pch = market$dend6, main = 'k = 6 Hierarchical')
par(mfrow = c(1, 1), mar = c(5, 4, 4, 2) + 0.1)
```

```{r}
library(dplyr)
labels <- as.data.frame(market %>%
                          group_by(dend6) %>%
                          summarise(avg_age = median(age), 
                                    avg_inc = median(income)))
```

```{r}
plot(market$age, market$income, col = market$dend6,
     pch = market$dend6 - 1, xlab = "Age", ylab = "Income",
     main = 'Marketing Clusters from Hierarchical Clustering \n (Labels
     show medians of age and income for cluster)')
points(labels[ ,2], labels[ ,3], pch = 21, col = 'maroon',
       bg = 'white', cex = 3)
text(labels[ ,2], labels[ ,3], cex = 1.1, col = 'black',
     labels[ ,1])

```

```{r}
market %>% group_by(dend6) %>% summarise(ClusterSize=n())
```

```{r}
data=market %>% group_by(dend6) %>% summarise(min_age=min(age), 
                                              med_age=median(age),
                                              max_age=max(age), 
                                              min_inc=min(income), 
                                              med_inc=median(income), 
                                              max_inc=max(income))
```

```{r}
label = c('old and rich','mid career with mid income', 'young and broke', 'pension', 'old and broke', 'Old Money')
data$labels = label
data
```
